input {
  beats {
    port => 5044
  }
}
filter {
  if [message] =~ "UFW BLOCK" {
    grok {
      match => { "message" => "SRC=%{IP:source_ip}" }
    }
  }
  else if [message] =~ "Failed password" {
    grok {
      match => { "message" => "Failed password for (invalid user )?%{USER:target_user} from %{IP:source_ip} port %{NUMBER:source_port}" }
    }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "security-lab-%{+YYYY.MM.dd}"
  }
}
